In [60]:
class Program:
    def __Division__(self, input1, input2):
        try:
            result=input1/input2
            print("%i Division %i = %i"% (input1, input2, result)) 
        except ZeroDivisionError as error:
            print("run time error: ", error)

Obj = Program()

Obj.__Division__(5,4)

5 Division 4 = 1


In [61]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]


print(subjects[0],verbs[0],objects[0])
print(subjects[0],verbs[0],objects[1])
print(subjects[0],verbs[1],objects[0])
print(subjects[0],verbs[1],objects[1])

print(subjects[1],verbs[0],objects[0])
print(subjects[1],verbs[0],objects[1])
print(subjects[1],verbs[1],objects[0])
print(subjects[1],verbs[1],objects[1])

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [62]:
import numpy as np
import pandas as pd



In [64]:
x = np.array([1, 2, 3, 4])
def vandermonde(arr, n):
    output = np.column_stack(x**(n-i-1) for i in range(n))
    return output

print(vandermonde(x, 3))

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
